export const PERMISSION_SLUG = {
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_DELETE: 'users:delete',
  ROLES_READ: 'roles:read',
  ROLES_WRITE: 'roles:write',
  ROLES_DELETE: 'roles:delete',
  PERMISSIONS_READ: 'permissions:read',
  PERMISSIONS_WRITE: 'permissions:write',
  PERMISSIONS_DELETE: 'permissions:delete',
  ORGANIZATIONS_READ: 'organizations:read',
  ORGANIZATIONS_WRITE: 'organizations:write',
  ORGANIZATIONS_DELETE: 'organizations:delete',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
  CUSTOMERS_READ: 'customers:read',
  CUSTOMERS_WRITE: 'customers:write',
  CUSTOMERS_DELETE: 'customers:delete',
  SUPPLIERS_READ: 'suppliers:read',
  SUPPLIERS_WRITE: 'suppliers:write',
  SUPPLIERS_DELETE: 'suppliers:delete',
  BRANDS_READ: 'brands:read',
  BRANDS_WRITE: 'brands:write',
  BRANDS_DELETE: 'brands:delete',
  CATEGORIES_READ: 'categories:read',
  CATEGORIES_WRITE: 'categories:write',
  CATEGORIES_DELETE: 'categories:delete',
  WAREHOUSES_READ: 'warehouses:read',
  WAREHOUSES_WRITE: 'warehouses:write',
  WAREHOUSES_DELETE: 'warehouses:delete',
  PRODUCTS_READ: 'products:read',
  PRODUCTS_WRITE: 'products:write',
  PRODUCTS_DELETE: 'products:delete',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  PURCHASES_READ: 'purchases:read',
  PURCHASES_WRITE: 'purchases:write',
  PURCHASES_DELETE: 'purchases:delete',
  PURCHASE_RETURNS_READ: 'purchase-returns:read',
  PURCHASE_RETURNS_WRITE: 'purchase-returns:write',
  PURCHASE_RETURNS_DELETE: 'purchase-returns:delete',
  SALES_READ: 'sales:read',
  SALES_WRITE: 'sales:write',
  SALES_DELETE: 'sales:delete',
  SALE_RETURNS_READ: 'sale-returns:read',
  SALE_RETURNS_WRITE: 'sale-returns:write',
  SALE_RETURNS_DELETE: 'sale-returns:delete',
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_WRITE: 'payments:write',
  PAYMENTS_DELETE: 'payments:delete',
  EXPENSES_READ: 'expenses:read',
  EXPENSES_WRITE: 'expenses:write',
  EXPENSES_DELETE: 'expenses:delete',
  DASHBOARD_READ: 'dashboard:read',
  REPORTS_READ: 'reports:read',
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_WRITE: 'notifications:write',
  AUDIT_READ: 'audit:read',
  UPLOADS_READ: 'uploads:read',
  UPLOADS_WRITE: 'uploads:write',
  UPLOADS_DELETE: 'uploads:delete',
} as const;

export type PermissionSlug =
  (typeof PERMISSION_SLUG)[keyof typeof PERMISSION_SLUG];

export const SYSTEM_PERMISSIONS = [
  {
    name: 'Read Users',
    slug: PERMISSION_SLUG.USERS_READ,
    module: 'users',
    description: 'View users and profiles',
    isSystem: true,
  },
  {
    name: 'Write Users',
    slug: PERMISSION_SLUG.USERS_WRITE,
    module: 'users',
    description: 'Update user profile, role, and status',
    isSystem: true,
  },
  {
    name: 'Delete Users',
    slug: PERMISSION_SLUG.USERS_DELETE,
    module: 'users',
    description: 'Delete users',
    isSystem: true,
  },
  {
    name: 'Read Roles',
    slug: PERMISSION_SLUG.ROLES_READ,
    module: 'roles',
    description: 'View roles',
    isSystem: true,
  },
  {
    name: 'Write Roles',
    slug: PERMISSION_SLUG.ROLES_WRITE,
    module: 'roles',
    description: 'Create and update roles',
    isSystem: true,
  },
  {
    name: 'Delete Roles',
    slug: PERMISSION_SLUG.ROLES_DELETE,
    module: 'roles',
    description: 'Delete custom roles',
    isSystem: true,
  },
  {
    name: 'Read Permissions',
    slug: PERMISSION_SLUG.PERMISSIONS_READ,
    module: 'permissions',
    description: 'View permissions and role assignments',
    isSystem: true,
  },
  {
    name: 'Write Permissions',
    slug: PERMISSION_SLUG.PERMISSIONS_WRITE,
    module: 'permissions',
    description: 'Create permissions and assign to roles',
    isSystem: true,
  },
  {
    name: 'Delete Permissions',
    slug: PERMISSION_SLUG.PERMISSIONS_DELETE,
    module: 'permissions',
    description: 'Delete custom permissions',
    isSystem: true,
  },
  {
    name: 'Read Organizations',
    slug: PERMISSION_SLUG.ORGANIZATIONS_READ,
    module: 'organizations',
    description: 'View organization details',
    isSystem: true,
  },
  {
    name: 'Write Organizations',
    slug: PERMISSION_SLUG.ORGANIZATIONS_WRITE,
    module: 'organizations',
    description: 'Create and update organizations',
    isSystem: true,
  },
  {
    name: 'Delete Organizations',
    slug: PERMISSION_SLUG.ORGANIZATIONS_DELETE,
    module: 'organizations',
    description: 'Deactivate organizations',
    isSystem: true,
  },
  {
    name: 'Read Settings',
    slug: PERMISSION_SLUG.SETTINGS_READ,
    module: 'settings',
    description: 'View organization settings',
    isSystem: true,
  },
  {
    name: 'Write Settings',
    slug: PERMISSION_SLUG.SETTINGS_WRITE,
    module: 'settings',
    description: 'Update organization settings',
    isSystem: true,
  },
  {
    name: 'Read Customers',
    slug: PERMISSION_SLUG.CUSTOMERS_READ,
    module: 'customers',
    description: 'View customers',
    isSystem: true,
  },
  {
    name: 'Write Customers',
    slug: PERMISSION_SLUG.CUSTOMERS_WRITE,
    module: 'customers',
    description: 'Create and update customers',
    isSystem: true,
  },
  {
    name: 'Delete Customers',
    slug: PERMISSION_SLUG.CUSTOMERS_DELETE,
    module: 'customers',
    description: 'Delete or deactivate customers',
    isSystem: true,
  },
  {
    name: 'Read Suppliers',
    slug: PERMISSION_SLUG.SUPPLIERS_READ,
    module: 'suppliers',
    description: 'View suppliers',
    isSystem: true,
  },
  {
    name: 'Write Suppliers',
    slug: PERMISSION_SLUG.SUPPLIERS_WRITE,
    module: 'suppliers',
    description: 'Create and update suppliers',
    isSystem: true,
  },
  {
    name: 'Delete Suppliers',
    slug: PERMISSION_SLUG.SUPPLIERS_DELETE,
    module: 'suppliers',
    description: 'Delete or deactivate suppliers',
    isSystem: true,
  },
  {
    name: 'Read Brands',
    slug: PERMISSION_SLUG.BRANDS_READ,
    module: 'brands',
    description: 'View brands',
    isSystem: true,
  },
  {
    name: 'Write Brands',
    slug: PERMISSION_SLUG.BRANDS_WRITE,
    module: 'brands',
    description: 'Create and update brands',
    isSystem: true,
  },
  {
    name: 'Delete Brands',
    slug: PERMISSION_SLUG.BRANDS_DELETE,
    module: 'brands',
    description: 'Delete or deactivate brands',
    isSystem: true,
  },
  {
    name: 'Read Categories',
    slug: PERMISSION_SLUG.CATEGORIES_READ,
    module: 'categories',
    description: 'View categories',
    isSystem: true,
  },
  {
    name: 'Write Categories',
    slug: PERMISSION_SLUG.CATEGORIES_WRITE,
    module: 'categories',
    description: 'Create and update categories',
    isSystem: true,
  },
  {
    name: 'Delete Categories',
    slug: PERMISSION_SLUG.CATEGORIES_DELETE,
    module: 'categories',
    description: 'Delete or deactivate categories',
    isSystem: true,
  },
  {
    name: 'Read Warehouses',
    slug: PERMISSION_SLUG.WAREHOUSES_READ,
    module: 'warehouses',
    description: 'View warehouses',
    isSystem: true,
  },
  {
    name: 'Write Warehouses',
    slug: PERMISSION_SLUG.WAREHOUSES_WRITE,
    module: 'warehouses',
    description: 'Create and update warehouses',
    isSystem: true,
  },
  {
    name: 'Delete Warehouses',
    slug: PERMISSION_SLUG.WAREHOUSES_DELETE,
    module: 'warehouses',
    description: 'Delete or deactivate warehouses',
    isSystem: true,
  },
  {
    name: 'Read Products',
    slug: PERMISSION_SLUG.PRODUCTS_READ,
    module: 'products',
    description: 'View products',
    isSystem: true,
  },
  {
    name: 'Write Products',
    slug: PERMISSION_SLUG.PRODUCTS_WRITE,
    module: 'products',
    description: 'Create and update products',
    isSystem: true,
  },
  {
    name: 'Delete Products',
    slug: PERMISSION_SLUG.PRODUCTS_DELETE,
    module: 'products',
    description: 'Delete or deactivate products',
    isSystem: true,
  },
  {
    name: 'Read Inventory',
    slug: PERMISSION_SLUG.INVENTORY_READ,
    module: 'inventory',
    description: 'View inventory stocks and movements',
    isSystem: true,
  },
  {
    name: 'Write Inventory',
    slug: PERMISSION_SLUG.INVENTORY_WRITE,
    module: 'inventory',
    description: 'Adjust inventory stock',
    isSystem: true,
  },
  {
    name: 'Read Purchases',
    slug: PERMISSION_SLUG.PURCHASES_READ,
    module: 'purchases',
    description: 'View purchase orders',
    isSystem: true,
  },
  {
    name: 'Write Purchases',
    slug: PERMISSION_SLUG.PURCHASES_WRITE,
    module: 'purchases',
    description: 'Create, update, and receive purchase orders',
    isSystem: true,
  },
  {
    name: 'Delete Purchases',
    slug: PERMISSION_SLUG.PURCHASES_DELETE,
    module: 'purchases',
    description: 'Cancel purchase orders',
    isSystem: true,
  },
  {
    name: 'Read Purchase Returns',
    slug: PERMISSION_SLUG.PURCHASE_RETURNS_READ,
    module: 'purchase-returns',
    description: 'View purchase returns',
    isSystem: true,
  },
  {
    name: 'Write Purchase Returns',
    slug: PERMISSION_SLUG.PURCHASE_RETURNS_WRITE,
    module: 'purchase-returns',
    description: 'Create purchase returns',
    isSystem: true,
  },
  {
    name: 'Delete Purchase Returns',
    slug: PERMISSION_SLUG.PURCHASE_RETURNS_DELETE,
    module: 'purchase-returns',
    description: 'Cancel purchase returns',
    isSystem: true,
  },
  {
    name: 'Read Sales',
    slug: PERMISSION_SLUG.SALES_READ,
    module: 'sales',
    description: 'View sales / invoices',
    isSystem: true,
  },
  {
    name: 'Write Sales',
    slug: PERMISSION_SLUG.SALES_WRITE,
    module: 'sales',
    description: 'Create and update sales',
    isSystem: true,
  },
  {
    name: 'Delete Sales',
    slug: PERMISSION_SLUG.SALES_DELETE,
    module: 'sales',
    description: 'Cancel draft sales',
    isSystem: true,
  },
  {
    name: 'Read Sale Returns',
    slug: PERMISSION_SLUG.SALE_RETURNS_READ,
    module: 'sale-returns',
    description: 'View sale returns',
    isSystem: true,
  },
  {
    name: 'Write Sale Returns',
    slug: PERMISSION_SLUG.SALE_RETURNS_WRITE,
    module: 'sale-returns',
    description: 'Create sale returns',
    isSystem: true,
  },
  {
    name: 'Delete Sale Returns',
    slug: PERMISSION_SLUG.SALE_RETURNS_DELETE,
    module: 'sale-returns',
    description: 'Cancel sale returns',
    isSystem: true,
  },
  {
    name: 'Read Payments',
    slug: PERMISSION_SLUG.PAYMENTS_READ,
    module: 'payments',
    description: 'View payments',
    isSystem: true,
  },
  {
    name: 'Write Payments',
    slug: PERMISSION_SLUG.PAYMENTS_WRITE,
    module: 'payments',
    description: 'Record payments in / out',
    isSystem: true,
  },
  {
    name: 'Delete Payments',
    slug: PERMISSION_SLUG.PAYMENTS_DELETE,
    module: 'payments',
    description: 'Reverse or delete payments',
    isSystem: true,
  },
  {
    name: 'Read Expenses',
    slug: PERMISSION_SLUG.EXPENSES_READ,
    module: 'expenses',
    description: 'View expenses and expense categories',
    isSystem: true,
  },
  {
    name: 'Write Expenses',
    slug: PERMISSION_SLUG.EXPENSES_WRITE,
    module: 'expenses',
    description: 'Create and update expenses / categories',
    isSystem: true,
  },
  {
    name: 'Delete Expenses',
    slug: PERMISSION_SLUG.EXPENSES_DELETE,
    module: 'expenses',
    description: 'Delete expenses and expense categories',
    isSystem: true,
  },
  {
    name: 'Read Dashboard',
    slug: PERMISSION_SLUG.DASHBOARD_READ,
    module: 'dashboard',
    description: 'View dashboard summaries and charts',
    isSystem: true,
  },
  {
    name: 'Read Reports',
    slug: PERMISSION_SLUG.REPORTS_READ,
    module: 'reports',
    description: 'View business reports',
    isSystem: true,
  },
  {
    name: 'Read Notifications',
    slug: PERMISSION_SLUG.NOTIFICATIONS_READ,
    module: 'notifications',
    description: 'View notifications',
    isSystem: true,
  },
  {
    name: 'Write Notifications',
    slug: PERMISSION_SLUG.NOTIFICATIONS_WRITE,
    module: 'notifications',
    description: 'Create, update, and delete notifications',
    isSystem: true,
  },
  {
    name: 'Read Audit',
    slug: PERMISSION_SLUG.AUDIT_READ,
    module: 'audit',
    description: 'View audit logs',
    isSystem: true,
  },
  {
    name: 'Read Uploads',
    slug: PERMISSION_SLUG.UPLOADS_READ,
    module: 'uploads',
    description: 'View uploaded files',
    isSystem: true,
  },
  {
    name: 'Write Uploads',
    slug: PERMISSION_SLUG.UPLOADS_WRITE,
    module: 'uploads',
    description: 'Upload new files',
    isSystem: true,
  },
  {
    name: 'Delete Uploads',
    slug: PERMISSION_SLUG.UPLOADS_DELETE,
    module: 'uploads',
    description: 'Delete uploaded files',
    isSystem: true,
  },
] as const;

/** Default permission slugs granted per system role */
export const ROLE_DEFAULT_PERMISSIONS: Record<string, PermissionSlug[]> = {
  SUPER_ADMIN: Object.values(PERMISSION_SLUG),
  ADMIN: [
    PERMISSION_SLUG.USERS_READ,
    PERMISSION_SLUG.USERS_WRITE,
    PERMISSION_SLUG.ROLES_READ,
    PERMISSION_SLUG.PERMISSIONS_READ,
    PERMISSION_SLUG.ORGANIZATIONS_READ,
    PERMISSION_SLUG.ORGANIZATIONS_WRITE,
    PERMISSION_SLUG.SETTINGS_READ,
    PERMISSION_SLUG.SETTINGS_WRITE,
    PERMISSION_SLUG.CUSTOMERS_READ,
    PERMISSION_SLUG.CUSTOMERS_WRITE,
    PERMISSION_SLUG.CUSTOMERS_DELETE,
    PERMISSION_SLUG.SUPPLIERS_READ,
    PERMISSION_SLUG.SUPPLIERS_WRITE,
    PERMISSION_SLUG.SUPPLIERS_DELETE,
    PERMISSION_SLUG.BRANDS_READ,
    PERMISSION_SLUG.BRANDS_WRITE,
    PERMISSION_SLUG.BRANDS_DELETE,
    PERMISSION_SLUG.CATEGORIES_READ,
    PERMISSION_SLUG.CATEGORIES_WRITE,
    PERMISSION_SLUG.CATEGORIES_DELETE,
    PERMISSION_SLUG.WAREHOUSES_READ,
    PERMISSION_SLUG.WAREHOUSES_WRITE,
    PERMISSION_SLUG.WAREHOUSES_DELETE,
    PERMISSION_SLUG.PRODUCTS_READ,
    PERMISSION_SLUG.PRODUCTS_WRITE,
    PERMISSION_SLUG.PRODUCTS_DELETE,
    PERMISSION_SLUG.INVENTORY_READ,
    PERMISSION_SLUG.INVENTORY_WRITE,
    PERMISSION_SLUG.PURCHASES_READ,
    PERMISSION_SLUG.PURCHASES_WRITE,
    PERMISSION_SLUG.PURCHASES_DELETE,
    PERMISSION_SLUG.PURCHASE_RETURNS_READ,
    PERMISSION_SLUG.PURCHASE_RETURNS_WRITE,
    PERMISSION_SLUG.PURCHASE_RETURNS_DELETE,
    PERMISSION_SLUG.SALES_READ,
    PERMISSION_SLUG.SALES_WRITE,
    PERMISSION_SLUG.SALES_DELETE,
    PERMISSION_SLUG.SALE_RETURNS_READ,
    PERMISSION_SLUG.SALE_RETURNS_WRITE,
    PERMISSION_SLUG.SALE_RETURNS_DELETE,
    PERMISSION_SLUG.PAYMENTS_READ,
    PERMISSION_SLUG.PAYMENTS_WRITE,
    PERMISSION_SLUG.PAYMENTS_DELETE,
    PERMISSION_SLUG.EXPENSES_READ,
    PERMISSION_SLUG.EXPENSES_WRITE,
    PERMISSION_SLUG.EXPENSES_DELETE,
    PERMISSION_SLUG.DASHBOARD_READ,
    PERMISSION_SLUG.REPORTS_READ,
    PERMISSION_SLUG.NOTIFICATIONS_READ,
    PERMISSION_SLUG.NOTIFICATIONS_WRITE,
    PERMISSION_SLUG.AUDIT_READ,
    PERMISSION_SLUG.UPLOADS_READ,
    PERMISSION_SLUG.UPLOADS_WRITE,
    PERMISSION_SLUG.UPLOADS_DELETE,
  ],
  MANAGER: [
    PERMISSION_SLUG.USERS_READ,
    PERMISSION_SLUG.ROLES_READ,
    PERMISSION_SLUG.PERMISSIONS_READ,
    PERMISSION_SLUG.ORGANIZATIONS_READ,
    PERMISSION_SLUG.SETTINGS_READ,
    PERMISSION_SLUG.CUSTOMERS_READ,
    PERMISSION_SLUG.CUSTOMERS_WRITE,
    PERMISSION_SLUG.SUPPLIERS_READ,
    PERMISSION_SLUG.SUPPLIERS_WRITE,
    PERMISSION_SLUG.BRANDS_READ,
    PERMISSION_SLUG.BRANDS_WRITE,
    PERMISSION_SLUG.CATEGORIES_READ,
    PERMISSION_SLUG.CATEGORIES_WRITE,
    PERMISSION_SLUG.WAREHOUSES_READ,
    PERMISSION_SLUG.WAREHOUSES_WRITE,
    PERMISSION_SLUG.PRODUCTS_READ,
    PERMISSION_SLUG.PRODUCTS_WRITE,
    PERMISSION_SLUG.INVENTORY_READ,
    PERMISSION_SLUG.INVENTORY_WRITE,
    PERMISSION_SLUG.PURCHASES_READ,
    PERMISSION_SLUG.PURCHASES_WRITE,
    PERMISSION_SLUG.PURCHASE_RETURNS_READ,
    PERMISSION_SLUG.PURCHASE_RETURNS_WRITE,
    PERMISSION_SLUG.SALES_READ,
    PERMISSION_SLUG.SALES_WRITE,
    PERMISSION_SLUG.SALE_RETURNS_READ,
    PERMISSION_SLUG.SALE_RETURNS_WRITE,
    PERMISSION_SLUG.PAYMENTS_READ,
    PERMISSION_SLUG.PAYMENTS_WRITE,
    PERMISSION_SLUG.EXPENSES_READ,
    PERMISSION_SLUG.EXPENSES_WRITE,
    PERMISSION_SLUG.DASHBOARD_READ,
    PERMISSION_SLUG.REPORTS_READ,
    PERMISSION_SLUG.NOTIFICATIONS_READ,
    PERMISSION_SLUG.NOTIFICATIONS_WRITE,
    PERMISSION_SLUG.AUDIT_READ,
    PERMISSION_SLUG.UPLOADS_READ,
    PERMISSION_SLUG.UPLOADS_WRITE,
  ],
  EMPLOYEE: [
    PERMISSION_SLUG.USERS_READ,
    PERMISSION_SLUG.ORGANIZATIONS_READ,
    PERMISSION_SLUG.SETTINGS_READ,
    PERMISSION_SLUG.CUSTOMERS_READ,
    PERMISSION_SLUG.CUSTOMERS_WRITE,
    PERMISSION_SLUG.SUPPLIERS_READ,
    PERMISSION_SLUG.SUPPLIERS_WRITE,
    PERMISSION_SLUG.BRANDS_READ,
    PERMISSION_SLUG.CATEGORIES_READ,
    PERMISSION_SLUG.WAREHOUSES_READ,
    PERMISSION_SLUG.PRODUCTS_READ,
    PERMISSION_SLUG.PRODUCTS_WRITE,
    PERMISSION_SLUG.INVENTORY_READ,
    PERMISSION_SLUG.INVENTORY_WRITE,
    PERMISSION_SLUG.PURCHASES_READ,
    PERMISSION_SLUG.PURCHASES_WRITE,
    PERMISSION_SLUG.PURCHASE_RETURNS_READ,
    PERMISSION_SLUG.PURCHASE_RETURNS_WRITE,
    PERMISSION_SLUG.SALES_READ,
    PERMISSION_SLUG.SALES_WRITE,
    PERMISSION_SLUG.SALE_RETURNS_READ,
    PERMISSION_SLUG.SALE_RETURNS_WRITE,
    PERMISSION_SLUG.PAYMENTS_READ,
    PERMISSION_SLUG.PAYMENTS_WRITE,
    PERMISSION_SLUG.EXPENSES_READ,
    PERMISSION_SLUG.EXPENSES_WRITE,
    PERMISSION_SLUG.DASHBOARD_READ,
    PERMISSION_SLUG.NOTIFICATIONS_READ,
    PERMISSION_SLUG.UPLOADS_READ,
    PERMISSION_SLUG.UPLOADS_WRITE,
  ],
};
